function signup() {
    document.getElementById("wow").innerHTML = '<a href="#" onclick="exit()" id="exit">x</a>'
    document.getElementById("signup2").innerHTML = '<img src="manhinh2.png" width="100%"><img src="manhinhphu.png" width=100% id="phu"><div id="signup"><h2 id="sign">Sign up here</h2><form action="new.php" method="POST"><input type="text" id="name" name="name" placeholder="Enter Name Here" required="required"><br><input type="email" id="email" name="email" placeholder="Enter Email Here" required="required"><br><input type="password" id="password" name="password" placeholder="Enter Password Here" required="required"><button id="sign_up">Sign up</button></form></div>'
    document.getElementById("backand").innerHTML = ""
}
function exit() {
    document.getElementById("backand").innerHTML ='<div id="background"><div id="praroz">PraRoz</div></div><div id="menu"><a href="#">HOME</a><a href="#">ABOUT</a><a href="#">SERVICE</a><a href="#">DESIGN</a><a href="#">CONTACT</a></div><div id="search"><input type="text" placeholder="Type To text" id="srch"><a href="#"><button id="btnsrch" onclick="init()">Search</button></a></div><div id="content"><h1>Web Desgin &</h1><h1 id="de">Development</h1><h1>Course</h1><p id="noidung">Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus culpa<br>voluptatem vero laborum provident, sequi mollitia molestiae soluta totam aut voluptatum quod, laudantium<br>cum, iure alias pariatur quasi possimus.</p><a href="#" id="joinus">JOIN US</a><div id="dangnhap"><h2>Login Here</h2><form action="newkk.php" method="POST"><input type="email" placeholder="Enter Email Here" name="email" value="" required="required"><input type="password" placeholder="Enter Password Here" id="pass" name="password" value="" required="required"><button id="login">Login</button></form><p id="don">Don\'t have an account</p><a onclick="signup()" id="signhere" href="#">Sign up</a><p id="log">Log in with</p><div id="icon"><a href="https://www.facebook.com"><ion-icon name="logo-facebook""></ion-icon></a><a href="https://www.instagram.com"><ion-icon name="logo-instagram"></ion-icon></a><a href="https://twitter.com"><ion-icon name="logo-twitter"></ion-icon></a><a href="https://www.google.com.vn/?hl=vi"><ion-icon name="logo-google"></ion-icon></a><a href="https://www.skype.com/en/"><ion-icon name="logo-skype"></ion-icon></a></div></div></div><script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>'
    document.getElementById("signup2").innerHTML = ''
    document.getElementById("wow").innerHTML = ''
}